### PR TITLE
Created a slideshow using the bootstrap carousel

### PR DESCRIPTION
**Pull request by Nancy4510**

### CODE REVIEW

**Comment by basuinfotech** [comment]
Thank you for your contribution !! keep contributing :heart:

**Comment by Nancy4510** [comment]
Thank you! I would certainly like to contribute to the other issues as well if that's okay.

**Comment by basuinfotech** [comment]
> Thank you! I would certainly like to contribute to the other issues as well if that's okay.

Please go ahead and keep contributing,  we will be very happy to see your PRs 😃

**Comment by Nancy4510** [comment]
Thank you!

**Pull request merged**
