### PR TITLE
Footer type 4 created

### PR DESCRIPTION
**Pull request by Abhiramborige**
Used basic bootstrap and css effects and responsive

### CODE REVIEW

**Comment by Abhiramborige** [comment]
Please check this. And thanks for giving chance to be a part of your project and open source !!

**Comment by Abhiramborige** [comment]
Hey!!. Can u please accept my PR if u like it, as soon as possible please

**Comment by basuinfotech** [comment]
Can you please change your footer design folder name to "footer - 5" , because "footer - 4" is already present .

**Comment by Abhiramborige** [comment]
So do i have to make a PR again??

**Comment by Abhiramborige** [comment]
The other footer was made after 1hr of mine,
Do i have to change the name and make PR??

**Comment by Abhiramborige** [comment]
Bro done. Please look into it

**Comment by Abhiramborige** [comment]
Please see the PR that i have made
Added footer-5

**Pull request closed without merging**
